name: experiment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.2
  - networkx==3.4.2
  - matplotlib==3.10.0
  - numpy==2.2.2
  - PyYAML==6.0.2
  - scipy==1.15.1
  - pandas==2.2.3
  - tqdm==4.67.1
  - optuna==4.3.0
